creation_rules:
  - encrypted_regex: '^(data|stringData|caBundle)$'
    path_regex: 'zitadel/.*\.sops\.ya?ml$'
    age: >-
      age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
  - path_regex: '.*-secret\.sops\.ya?ml$'
    age: >-
      age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj