apiVersion: v1
kind: Secret
metadata:
    name: zitadel-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QURwZURdQ54tedS8U/8I+ogXXfA811SVPA==,iv:sApUBh/y1XYvRdXSQFxZPAwV9lFhI35tU0wD1XgMNPE=,tag:G2x+mWV5Q6l8XXvuBH6WYQ==,type:str]
    password: ENC[AES256_GCM,data:iOFAbxbn85gZpxf43W3N2aqAWQi3uObFMYAD0uk=,iv:wkUNCOzv81rZowH22W4NnhTWpDIFm1ny0JV2iRfm9Qc=,tag:q7EnR0jHYTfmd9vB0mtpKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGQ3cjEyNXoydjEzaFpZ
            dGpWV0I1c2hpUElwYjAyVzRzV0s4T1F3WGg0ClF5ZHg3VDVyOFNnZlUwUVNNWUp3
            b1pxTmpKcjhQWjZqb0UrVVdKUjhlencKLS0tIDBIRC9NSE9EVTYzc29jQ1BGaEs1
            ckhCdWRBeXdzaFNIeTI4VmlqL1JYRVUKHoBWCA3QAM07cMQzRWfSNeYatkDAckfl
            PQnOgaxm1EhLaLcUz7O1Lx8LaKUD5d7Tt9cr4L+DGFT1+Xw1kA2tFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T20:13:03Z"
    mac: ENC[AES256_GCM,data:5LuBIhzvZH1t5bhL3WNmPWPCnFp2lK7CfXY2DZwUsu012xBDVeNFIGq1cPQGGQ5pr+t27HFs8/rD4H+f64PU5PgV2rg9WDrhqn4VMKROwL+p6L+uZ57E167W/726TLKLTyDexEl9lPQB2t61Mofi6tMPoG8VB+rvG26lrAGwvYs=,iv:8vu7nYqiUu0NirsxdDawtzGCeotV8aCPMMGMm6+jgQ8=,tag:hAxe9YzmApHofeArg/YLYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
